### ISSUE TITLE
Running example locally

### ISSUE THREAD

**Issue by donrabaya** [allartk/leaflet.offline#205]
Hello,

Encountered an error when trying to run the example locally.

I have done these steps 

```
npm i && npm run build
cd docs
npm install && npm run serve
```

Now I am just getting "Cannot GET /" on localhost:9000

See screenshots for further details. Thank you!

<img width="1081" alt="Screenshot 2022-06-27 at 6 14 52 PM" src="https://user-images.githubusercontent.com/32283180/175919072-f4447573-b623-41d2-802c-0ef4a5b99c65.png">

![Uploading Screenshot 2022-06-27 at 6.14.52 PM.png…]()
<img width="327" alt="Screenshot 2022-06-27 at 6 15 50 PM" src="https://user-images.githubusercontent.com/32283180/175919095-9f1e16dc-1169-4aff-9338-a8eb08bc58ba.png">

**Comment by allartk** [comment]
Hi, the correct command at the moment is `npm start` (which requires docker)

**Comment by albfan** [comment]
```
$ npm start

> docs@1.0.0 start
> concurrently -n webpack,jekyll -k 'npm run serve' 'npm run jekyll'

[webpack] 
[webpack] > docs@1.0.0 serve
[webpack] > webpack serve --mode development
[webpack] 
[jekyll] 
[jekyll] > docs@1.0.0 jekyll
[jekyll] > docker-compose up
[jekyll] 
[jekyll] Starting docs_jekyll_1 ... 
[webpack] Browserslist: caniuse-lite is outdated. Please run:
[webpack]   npx browserslist@latest --update-db
[webpack]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[jekyll] Starting docs_jekyll_1 ... done
[jekyll] Attaching to docs_jekyll_1
[jekyll] jekyll_1  | ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
[webpack] <i> [webpack-dev-server] Project is running at:
[webpack] <i> [webpack-dev-server] Loopback: http://localhost:9000/
[webpack] <i> [webpack-dev-server] On Your Network (IPv4): http://192.168.48.198:9000/
[webpack] <i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::fb09:5587:b533:7e92]:9000/
[webpack] <i> [webpack-dev-server] Content not from webpack is served from '/home/alberto/projects/javascript/leaflet.offline/docs/_site' directory
[jekyll] jekyll_1  |              Fatal: The configuration file '/srv/jekyll/_config.yml' could not be found.
[jekyll] jekyll_1  | /usr/gem/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:181:in `rescue in read_config_file': The Configuration file '/srv/jekyll/_config.yml' could not be found. (LoadError)
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:165:in `read_config_file'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:198:in `block in read_config_files'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:195:in `each'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:195:in `read_config_files'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll.rb:118:in `configuration'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:44:in `configuration_from_options'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:83:in `block (2 levels) in init_with_program'
[jekyll] jekyll_1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
[jekyll] jekyll_1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
[jekyll] jekyll_1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
[jekyll] jekyll_1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
[jekyll] jekyll_1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
[jekyll] jekyll_1  | 	from /usr/gem/bin/jekyll:25:in `load'
[jekyll] jekyll_1  | 	from /usr/gem/bin/jekyll:25:in `<main>'
[jekyll] jekyll_1  | /usr/gem/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `initialize': Permission denied @ rb_sysopen - /srv/jekyll/_config.yml (Errno::EACCES)
[jekyll] jekyll_1  | 	from /usr/gem/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
[jekyll] jekyll_1  | 	from /usr/gem/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:129:in `safe_load_file'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:167:in `read_config_file'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:198:in `block in read_config_files'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:195:in `each'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/configuration.rb:195:in `read_config_files'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll.rb:118:in `configuration'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:44:in `configuration_from_options'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:83:in `block (2 levels) in init_with_program'
[jekyll] jekyll_1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
[jekyll] jekyll_1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
[jekyll] jekyll_1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
[jekyll] jekyll_1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
[jekyll] jekyll_1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
[jekyll] jekyll_1  | 	from /usr/gem/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
[jekyll] jekyll_1  | 	from /usr/gem/bin/jekyll:25:in `load'
[jekyll] jekyll_1  | 	from /usr/gem/bin/jekyll:25:in `<main>'
[jekyll] docs_jekyll_1 exited with code 1
npm run jekyll exited with code 0
--> Sending SIGTERM to other processes..
[webpack] <i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...
[webpack] npm run serve exited with code 0
```

Any other step is needed?
