### ISSUE TITLE
ERROR Error: Request failed with status 200

### ISSUE THREAD

**Issue by iyasilias** [allartk/leaflet.offline#25]
Full diagnosis:

```
Error: Request failed with status 200
    at XMLHttpRequest.xhr.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (http://localhost:8100/build/vendor.js:174277:15)
    at XMLHttpRequest.H (http://localhost:8100/build/polyfills.js:3:23950)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5125:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16794)
    at p (http://localhost:8100/build/polyfills.js:2:27648)
    at XMLHttpRequest.v (http://localhost:8100/build/polyfills.js:2:27893)
```

I am using your script in Ionic Framework, installed through `npm install leaflet.offline`.

I have checked my storage, the script does seem to capture the tiles into db
<img width="665" alt="screen shot 2018-07-28 at 3 50 30 am" src="https://user-images.githubusercontent.com/634151/43343607-7065760a-9219-11e8-99eb-487758b9d929.png">

Another problem is, type script won't recognise `.offline` and `.saveTiles`.
<img width="446" alt="screen shot 2018-07-28 at 3 53 54 am" src="https://user-images.githubusercontent.com/634151/43343725-e25cae22-9219-11e8-9b88-1e20d376cec3.png">

My compiler gives this error message:
```
[14:51:46]  typescript: src/pages/home-map-view2/home-map-view2.ts, line: 45 
            Property 'offline' does not exist on type 'typeof tileLayer'. 

[14:51:46]  typescript: src/pages/home-map-view2/home-map-view2.ts, line: 52 
      L44:  //offline baselayer, will use offline source if available
      L45:  var baseLayer = leaflet.tileLayer.offline('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      L46:      attribution: 'Map data {attribution.OpenStreetMap}',

            Property 'savetiles' does not exist on type 'typeof control'.
```

Please help. Thanks.

**Comment by allartk** [comment]
About the error, can you replicate using a codepen? Use https://codepen.io/allartk/pen/EpbPqo as a starter. I am not so familiar with ionic, but polyfill.js is not created by leaflet.offline. Using the same libraries in the browser should make it possible to replicate the error.

Also: I would be glad to see a pull request for typescript support. I do not use it in my daily work.

**Comment by allartk** [comment]
i close this, because no answer for long time

**Comment by philipgriffin** [comment]
I have also ran into this issue here's some more reference on it:
![leaflet](https://user-images.githubusercontent.com/17783426/61821755-e5a5ab80-ae4f-11e9-8cf9-1f5ab3b23bd6.gif)
