### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by Ludus731** [allartk/leaflet.offline#404]
OS: Windows 10

1. `npm init` in an empty project directory
2. `npm install leaflet.offline`
3. Create `index.js` with `import 'leaflet.offline'`
4. Add `"type": "module"` to `package.json`
5. `node index.js`

I’m getting the error:

```
C:\path\to\project\node_modules\leaflet\dist\leaflet-src.js:230
  var requestFn = window.requestAnimationFrame || getPrefixed('RequestAnimationFrame') || timeoutDefer;
                  ^

ReferenceError: window is not defined
    at C:\path\to\project\node_modules\leaflet\dist\leaflet-src.js:230:19
    at C:\path\to\project\node_modules\leaflet\dist\leaflet-src.js:7:66
    at Object.<anonymous> (C:\path\to\project\node_modules\leaflet\dist\leaflet-src.js:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at C:\path\to\project\node_modules\leaflet.offline\dist\bundle.js:2:85

Node.js v18.18.0
```

**Comment by allartk** [comment]
Seems you try to run on node and not in the browser?

The error is from leaflet itself, which should run in the browser.

**Comment by Ludus731** [comment]
> Seems you try to run on node and not in the browser?

Which file do I need to open in the browser after loading the package with `npm install leaflet.offline`? I only need to download and save the map tiles on my PC.

**Comment by allartk** [comment]
I hope the examples can help you,
